### ISSUE TITLE
TORA Controllers

### ISSUE THREAD

**Issue by dlshriver** [verivital/ARCH-COMP2021#1]
I was wondering if the ONNX model for the controller of the TORA benchmark is correct. It looks like it only uses ReLU activations, however the ARCH-COMP reports mention heterogeneous activations with both ReLU and Tanh. Is the model in this repo correct?

Additionally, there is a mention of a TORA controller with Sigmoid activations in the ARCH-COMP 2021 report, however I do not see a corresponding model included in this repo. Is it provided in a different location?

**Comment by schillic** [comment]
The non-ReLU networks are in [this folder](https://github.com/verivital/ARCH-COMP2021/tree/master/benchmarks/Tora_Heterogeneous).

**Comment by dlshriver** [comment]
Nevermind, I realize there is a separate directory for the heterogeneous TORA models. Thank you.
